config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'
  post 'admin/automate'
  post 'admin/add_exam'
  post 'admin/add_teacher'
  devise_for 'teachers', :controllers => {:registrations => "registrations"}
  root 'main#index'
  get 'main/index'
  get 'teachers/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
attr_accessor :unhashed_password
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable
  enum roles: {member: 0,admin: 1}

  # private 
  # def default_member
  #   self.roles=member
  #   puts
  # end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_teacher!,:is_admin
  def index
    @exams=Exam.all
    @teachers=Teacher.all
  end
  def automate
    automate_duties
    respond_to do |format|
        format.js{}
    end
  end
  def add_exam
    
     @exam = Exam.new(exam_params)

    respond_to do |format|
      if @exam.save
        format.html { redirect_to @exam, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @exam }
        format.js{ }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end
  def add_teacher
    
     @teacher = Teacher.new(teacher_params)
     @teacher.password="generated_password"
     print @teacher
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
        format.js{ }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end
  private
  def is_admin
    if current_teacher.admin? ==false
      redirect_to '/'
    end
  end
  def automate_duties
    
  end
  def exam_params
      if params['exam']
      params.require(:exam).permit(:course_id,:course,:time,:date,:cls,:room)
      end
    end

  def teacher_params
      if params['teacher']
      params.require(:teacher).permit(:name,:department,:email)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
    puts "Working"
    resource.unhashed_password = resource_params[:password]
    resource.send_confirmation_instructions
  end
end
# customize session controller

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_teacher!,:is_member
  def index
  end
  private
  def is_member
    if current_teacher.admin? == true
      redirect_to '/admin/index'
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/_exam_table_entry.html.erb
 <tr>
    <td><%=exam.course_id%></td>
    <td><%=exam.course%></td>
    <td><%=exam.date%></td>
    <td><%=exam.time.to_formatted_s(:time)%></td>
    <td><%=exam.cls%></td>
    <td><%=exam.room%></td>
</tr>

app/views/admin/_loader.html.erb
<style>
#loader-cover{
    position:fixed;
    background-color:rgba(0,0,0,0.5);
    top:0;
    bottom:0;
    left:0;
    right:0;
    display:flex;
    justify-content:center;
    align-items:center;

}
.lds-ring {
  display: inline-block;
  position: relative;
  width: 64px;
  height: 64px;
}
.lds-ring div {
  box-sizing: border-box;
  display: block;
  position: absolute;
  width: 51px;
  height: 51px;
  margin: 6px;
  border: 6px solid #fff;
  border-radius: 50%;
  animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
  border-color: #fff transparent transparent transparent;
}
.lds-ring div:nth-child(1) {
  animation-delay: -0.45s;
}
.lds-ring div:nth-child(2) {
  animation-delay: -0.3s;
}
.lds-ring div:nth-child(3) {
  animation-delay: -0.15s;
}
@keyframes lds-ring {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>

<div id="loader-cover">
<div class="lds-ring"><div></div><div></div><div></div><div></div></div>
</div>

app/views/admin/_teacher_table_entry.html.erb
<tr>
    <td><%=teacher.email %></td>
    <td><%=teacher.name %></td>
    <td><%=teacher.department %></td>
    <td><%=link_to('resend', teacher_confirmation_path(teacher: {:email => "#{teacher.email}"}), :method => :post,remote: true)%></td>
</tr>

app/views/admin/_teachers_duties.html.erb
HEllo

app/views/admin/add_exam.js.erb
$('.exams .table tbody').append('<%= escape_javascript(render 'exam_table_entry',exam:@exam)%>')
$('#loader-cover').remove()

app/views/admin/add_teacher.js.erb
$('.teachers .table tbody').append('<%= escape_javascript(render 'teacher_table_entry',teacher:@teacher)%>')
$('#loader-cover').remove()

app/views/admin/automate.js.erb
var automate = document.getElementById('automated_duties');
automate.append('<%= escape_javascript(render 'teachers_duties') %>')

app/views/admin/index.html.erb
<%= render 'main/navbar' %>

<div class="content">
    <div class="tables">
    <div class="teachers">
        <table class="table">
            <thead>
                <th>Email</th>
                <th>Name</th>
                <th>Department</th>
                <th>Resend</th>
            </thead>
            <tbody>
            <%@teachers.each do |teacher| %>
                <tr>
                    <td><%=teacher.email %></td>
                    <td><%=teacher.name %></td>
                    <td><%=teacher.department %></td>
                    <td><%=link_to('resend', teacher_confirmation_path(teacher: {:email => "#{teacher.email}"}), :method => :post,remote: true)%></td>
                  
                </tr>
            <%end%>
            </tbody>
        </table>
        <%=form_tag admin_add_teacher_path,{remote: true,method: :post,:class=>"add_exam"} do%>
            <h3>Add Teacher</h3>
            <%=text_field :teacher , :name,placeholder: "Name",required: true%>
            <%=email_field :teacher , :email,placeholder: "Email",required: true%><br>
            <%=text_field :teacher , :department,placeholder: "Department",required: true%>
            <%=submit_tag :Add%>
        <%end%>
       
    </div>
    <div class="exams">
    <table class="table">
            <thead>
                <tr>
                    <th>Exam Id</th>
                    <th>Course</th>
                    <th>Date</th>
                    <th>Timings</th>
                    <th>Class</th>
                    <th>Room</th>
                </tr>
            </thead>
            <tbody>
            <%@exams.each do|exam| %>
                <tr>
                    <td><%=exam.course_id%></td>
                    <td><%=exam.course%></td>
                    <td><%=exam.date%></td>
                    <td><%=exam.time.to_formatted_s(:time)%></td>
                    <td><%=exam.cls%></td>
                    <td><%=exam.room%></td>
                </tr>
                <%end %>
            </tbody>
        </table>
        <%=form_tag admin_add_exam_path,{remote: true,method: :post,:class=>"add_exam"} do%>
            <h3>Add Exam</h3>
            <%=text_field :exam , :course_id,placeholder: "Course Id",required: true%>
            <%=text_field :exam , :course,placeholder: "Course",required: true%><br>
            <%=date_field :exam , :date,required: true%>
            <%=time_field :exam , :time,required: true%><br>
            <%=text_field :exam , :cls,placeholder: "Class",required: true%>
            <%=text_field :exam , :room,placeholder: "Room",required: true%><br>
            <%=submit_tag :Add%>
        <%end%>
    </div>
    </div>
    <%=button_to 'Automate Duties',admin_automate_path,remote: true,method: :post%>
    <div id="automated_duties">
    </div>
</div>
<script>

    $('.add_exam input[type="submit"]').on('click',function (e) {
        $('body').append('<%=escape_javascript(render 'loader')%>')
        
    })

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teachersduty</title>
    <%= csrf_meta_tags %>
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"> 
    <%# <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <%# <%= stylesheet_link_tag params[:controller] %>
   <%=stylesheet_link_tag :application, (controller_name unless devise_controller?) unless (controller_name unless devise_controller?).nil?%>
   <%=javascript_include_tag :application, (controller_name unless devise_controller?) unless (controller_name unless devise_controller?).nil?%>
    <%# <%= stylesheet_link_tag 'application' %> 
        <%# <%= javascript_include_tag params[:controller] %>  


  </head>

  <body>
<script type="text/javascript" >
  <%if notice %>
    new Noty({
        type: 'info',
        layout: 'topRight',
        theme: 'mint',
        text: '<%= notice %>',
        timeout: 5000,
        progressBar: true,
        closeWith: ['click', 'button'],
        animation: {
            open: 'noty_effects_open',
            close: 'noty_effects_close'
        },
        id: false,
        force: false,
        killer: false,
        queue: 'global',
        container: false,
        buttons: [],
        sounds: {
            sources: [],
            volume: 1,
            conditions: []
        },
        titleCount: {
            conditions: []
        },
        modal: false
    }).show()
  <% end %>
  <%if alert%>
  new Noty({
      type: 'error',
      layout: 'topRight',
      theme: 'mint',
      text: '<%= alert %>',
      timeout: 5000,
      progressBar: true,
      closeWith: ['click', 'button'],
      animation: {
          open: 'noty_effects_open',
          close: 'noty_effects_close'
      },
      id: false,
      force: false,
      killer: false,
      queue: 'global',
      container: false,
      buttons: [],
      sounds: {
          sources: [],
          volume: 1,
          conditions: []
      },
      titleCount: {
          conditions: []
      },
      modal: false
  }).show()
<% end %>
</script>
    <%= yield %>
  </body>
</html>

app/views/main/_navbar.html.erb
<style>
nav {
  background-color: #f3f3f3;
  height: 50px;
  display: flex;
  justify-content: space-between;
  padding: 0px 20px;
}
/* line 10, /media/amit/disk H/amit/alchemy/teachersduty/app/assets/stylesheets/main.scss */
nav .Logo {
  display: flex;
  width: 175px;
  align-items: center;
  justify-content: space-between;
  font-weight:600;
}
/* line 16, /media/amit/disk H/amit/alchemy/teachersduty/app/assets/stylesheets/main.scss */
nav ul {
  list-style: none;
  display: flex;
  align-items: center;
  height: 100%;
  margin: 0;
  padding: 0;
}
/* line 23, /media/amit/disk H/amit/alchemy/teachersduty/app/assets/stylesheets/main.scss */
nav ul li {
  display: flex;
  align-items: center;
  height: 100%;
}
/* line 27, /media/amit/disk H/amit/alchemy/teachersduty/app/assets/stylesheets/main.scss */
nav ul li a {
  display: flex;
  align-items: center;
  padding: 0 15px;
  color: black;
  text-decoration: none;
  height: 100%;
}
/* line 35, /media/amit/disk H/amit/alchemy/teachersduty/app/assets/stylesheets/main.scss */
nav ul li a:hover {
  /*background-color: #ccc;*/
  border-bottom:5px solid grey;
  color: grey;
}
</style>
<nav>
    <div class="Logo">
        <%=image_tag 'LOGO(NIT).png',width:'50'%>
        <label>NIT Hamirpur</label>
    </div>
    <ul>
        <li><%=link_to 'Home',root_path%></li>
        <%if teacher_signed_in? %>
        <li><%=link_to 'Dashboard',teachers_index_path,method: :get%></li>
        <li><%=link_to current_teacher.email+'[logout]',destroy_teacher_session_path,method: :delete%></li>
        <%else %>
        <li><%=link_to 'SignIn',teachers_index_path%></li>
        <%end  %>
    </ul>
</nav>

app/views/main/index.html.erb
<%=render 'navbar'%>
<div class="top_banner">
    Teacher duty Assigner
</div>
<div class="main">
    
</div>

app/views/teachers/index.html.erb
<h1>Teachers#index</h1>
<p>Find me in app/views/teachers/index.html.erb</p>